language: clojure

branches:
  only:
    - source

sudo: required

cache:
  directories:
    - $HOME/.m2

lein: lein

dist: bionic

script: lein run

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: source
